name: Check PR Labels
on: 
  - pull_request

permissions:
  contents: read
  pull-requests: write
  issues: read
  checks: write

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get PR Labels
        id: get-labels
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;

            const { data: pr } = await github.rest.pulls.get({
              owner: owner,
              repo: repo,
              pull_number: pull_number
            });

            const labels = pr.labels.map(label => label.name);
            if (! labels.some(label => ["bug", "enhancement", "maintenance"].includes(label))) {
              core.setFailed("This pull request does not have any labels. Failing the job.");
            }

            // if (! labels.some(label => ["bug", "enhancement", "maintenance"].includes(label))) {
            // (labels.length === 0) {
            // switch the error condition to this in order to make it check for specific labels
