name: Check PR Labels

on:
  pull_request

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get PR Labels
        id: get-labels
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context, core } = require('@actions/github');
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const labels = pr.labels.map(label => label.name);
            if (labels.length === 0) {
              core.setFailed("This pull request does not have any labels. Failing the job.");
            }

            // Uncomment and replace the script content above with this block to require specific labels
            // const requiredLabels = ["bug", "enhancement", "maintenance"];
            // const hasRequiredLabel = labels.some(label => requiredLabels.includes(label));

            // if (!hasRequiredLabel) {
            //   core.setFailed("This pull request does not have the required label. Failing the job.");
            // }
 